# Generated by Django 2.0.6 on 2023-05-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('ggirlnum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('sgender', models.BooleanField()),
                ('scontend', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
                ('sgrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Grades')),
            ],
        ),
    ]
